module.exports = [
    { link: 1, Section: 'Selfie Drone' },
    { link: 2, Section: 'Best Drones for Beginners' },
    { link: 3, Section: 'Drones That Follow You' },
    { link: 4, Section: 'Camera Drones' },
    { link: 5, Section: 'Professional Drones' },
    { link: 6, Section: 'Gimbal Stabilizers' },
    { link: 7, Section: 'Drones for sale' },
    { link: 8, Section: 'Payment Methods' },
    { link: 9, Section: 'Order Information' },
    { link: 10, Section: 'Shipping & Delivery' },
    { link: 11, Section: 'Return Policy' },
    { link: 12, Section: 'Technical Support' },
    { link: 13, Section: 'After-Sales Service Policies' },
    { link: 14, Section: 'DJI Credit' },
    { link: 15, Section: 'Refurbished Products' },
    { link: 16, Section: 'Referral Program' },
    { link: 17, Section: 'DJI Select Membership' },
    { link: 18, Section: 'Educational Discount' },
    { link: 19, Section: 'Corporate Purchase Program' },
    { link: 20, Section: 'DJI Trade Up' },
    { link: 21, Section: 'DJI Affiliate Program' },
    { link: 22, Section: 'DJI Store App' },
    { link: 23, Section: 'SkyPixel' },
    { link: 24, Section: 'DJI Forum' },
    { link: 25, Section: 'Buying Guides' },

]